using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Windows.UI.Xaml.Controls;

namespace PrototypeTinder4Jobs.Controls
{
    public class CustomPhoneApplicationFrame : Frame
    {
        public CustomPhoneApplicationFrame()
        {
            
        }

        public void ShowPopupOffsetClicked()
        {

        }

        
    }
}
